### ISSUE TITLE
TypeError: URL.createObjectURL is not a function

### ISSUE THREAD

**Issue by ChristopherTrimboli** [lumalabs/luma-web-examples#11]
![image](https://github.com/lumalabs/luma-web-examples/assets/27584221/6046fb40-cc80-46ef-8d4c-0f1a88a18d63)

Noticed this runtime log in Vercel. Crashes some clients using Splats.

Seems `URL` is not polyfilled?

**Comment by haxiomic** [comment]
Thanks for the report

Interesting, these must be very old browsers
https://caniuse.com/?search=createObjectURL

These almost certainly won't support WebGL2 which is required

Best bet is to check for WebGL2 support and show a fallback if not. This should also catch these errors

Nothing we can do our side
