### ISSUE TITLE
how to get the particle shader like the demo

### ISSUE THREAD

**Issue by zhuhang4** [lumalabs/luma-web-examples#13]
the cloud point change to the splats effect is awesome! but i don't konw how to get these code.Anyone can help??

**Comment by koktavy** [comment]
There are hints here: [https://github.com/lumalabs/luma-web-examples/blob/main//src/DemoCustomShaders.ts](https://github.com/lumalabs/luma-web-examples/blob/main//src/DemoCustomShaders.ts)

I'm in the process of figuring it out in vanilla three.js myself.

**Comment by haxiomic** [comment]
Hi @zhuhang4, set `particleRevealEnabled: true` when creating a splat instance
```ts
new LumaSplatsThree({ particleRevealEnabled: true });
```
