### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by vpicavet** [lumalabs/luma-web-examples#2]
Hello,
Thank you for this library, gaussian splatting are progressing fast !

It seems that this repository lacks a proper mention of the licence applied. Could you specify it in the README and add a LICENSE file so that we know if it is opensource or not ?

The licence of the code can be different from the terms and conditions of the Luma service of course.

**Comment by oliver-batchelor** [comment]
Seconded - I don't think anyone can realistically use this without it?

**Comment by haxiomic** [comment]
1675e0ccd00d6eaa97ec1f8601f39de55d099126
