### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'equals')

### ISSUE THREAD

**Issue by lovelovetrb** [lumalabs/luma-web-examples#4]
Hello.
I am enjoying using Luma AI.
I am posting this issue because I have tried the WebGL library for Luma AI, but I have encountered some problems.

I wrote code based on three.js and the Luma WebGL example, but when I ran the code, nothing was rendered in the browser and I got a lot of errors in the console on the browser.
Below is the full text of the errors.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'equals')
    at setBlending (three.module.js:23355:19)
    at Object.setMaterial (three.module.js:23382:6)
    at WebGLRenderer.renderBufferDirect (three.module.js:29149:10)
    at renderObject (three.module.js:29945:11)
    at renderObjects (three.module.js:29914:6)
    at renderScene (three.module.js:29777:41)
    at WebGLRenderer.render (three.module.js:29593:5)
    at animate (main.js:31:12)
```

I think it might be a Luma AI WebGL issue, since the problem did not occur with the normal three.js example. Any advice would be appreciated.

Here is some information about my environment

### Code
code is [here](https://github.com/lovelovetrb/luma-ai-vanila)

### package.json
``` package.json
{
  "name": "luma-app-vanila",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.0.0"
  },
  "dependencies": {
    "@lumaai/luma-web": "^0.1.14",
    "three": "^0.159.0"
  }
}
```

### Node.js version
```
$ bun run node -v
v20.5.1
```

### Package Management Tools
```
$ bun --version
1.0.7
```

### LumaSplatsThree git version?
(This information is output to the browser console)
```
LumaSplatsThree git version #8f3367e
```

**Comment by haxiomic** [comment]
Hi @lovelovetrb, I tried your repo and it worked for me – I did have to change the three.js version in package json to r157

```json
"dependencies": {
    "@lumaai/luma-web": "^0.1.14",
    "three": "^0.157.0"
  }
  ```

My guess is there's been some breaking changes in three.js in the last two versions

Hopefully this change works for you too, let me know!

**Comment by haxiomic** [comment]
It also seems to work for me on r159 too, so I'm unclear on the cause

**Comment by lovelovetrb** [comment]
@haxiomic  Thank you very much! I changed the version and it worked.

With bun I changed the version and it did not run well. Why is this?
I can achieve what I want to do with npm, so I will continue to implement it with npm.

Thanks for your advice!
