### ISSUE TITLE
Library looking for specific files to load

### ISSUE THREAD

**Issue by GitHubDragonFly** [lumalabs/luma-web-examples#6]
I have given it a try and created an online [Luma SPLAT Viewer](https://githubdragonfly.github.io/viewers/templates/Luma%20SPLAT%20Viewer.html) using this library and three.js r159.

It currently only supports URL loading and it does work when using Luma URLs, like this:
- `https://lumalabs.ai/capture/ca9ea966-ca24-4ec1-ab0f-af665cb546ff`

The issue can be seen in the attached picture below when I use a URL like this:
- `https://raw.githubusercontent.com/GitHubDragonFly/GitHubDragonFly.github.io/main/viewers/examples/legobrick.splat`

The library is treating this URL as a "folder", or a location that hosts multiple files, and is trying to get 1 bin and 3 json files out of it.

If I try to use the [WebGL Gaussian Splat Viewer](https://antimatter15.com/splat/) then it works, and the following URL can just be entered in a browser:
- `https://antimatter15.com/splat/?url=https://raw.githubusercontent.com/GitHubDragonFly/GitHubDragonFly.github.io/main/viewers/examples/legobrick.splat`

This `legobrick.splat` file is just a lego brick made of points and was created from a ply file which was converted to splat by using the above mentioned WebGL Gaussian Splat Viewer.

The library also does not seem to be able to handle local blob URLs either, created with `URL.createObjectURL( splat_file )` , which is another issue.

I might be doing something wrong all together but just looking for a second opinion.

![SPLAT Viewer - Error](https://github.com/lumalabs/luma-web-examples/assets/69928501/af1df84a-8274-442a-a6e2-7faf099c3f08)

**Comment by GitHubDragonFly** [comment]
I just noticed that your repository is specifically stating:
- `path to a luma splats file or folder containing a luma splats artifacts`

That answers the question in my previous post.

Out of curiosity, how does one go about creating luma splat file?

**Comment by eggman28** [comment]
I am using luma.ai to create and download Gaussian Splat file but I just get a zip file with PLY file in it. I'm also trying to work out what is required to view splat files not hosted by luma and where we're meant to get these other required files that the console is showing as missing.

**Comment by GitHubDragonFly** [comment]
For those who might be interested, I have switched to using [@pmndrs/drei-vanilla](https://github.com/pmndrs/drei-vanilla#splat) and my new [SPLAT Viewer](https://githubdragonfly.github.io/viewers/templates/SPLAT%20Viewer.html) is currently using it and with the code available in my repository.

Also, the Luma Splat Viewer's link in my initial post was updated for those who might need that code and will wait for Luma developers to update this library.

I will close this topic.

**Comment by chillbert** [comment]
<img width="512" alt="image" src="https://github.com/lumalabs/luma-web-examples/assets/46078367/30a0ad80-488f-401e-849f-aadb70b97bd0">
@GitHubDragonFly Which format do I need to export from Lumalabs to be able to view it with the <Splat/> of drei? I tried the .ply or .splat; it's super slow or looks totally different than in the lumas npm package. Do I need somehow to convert the ply into splat correctly with some tool?

**Comment by GitHubDragonFly** [comment]
@chillbert there is only one thing I could suggest which is for you to visit my [webpage](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io) and read the description, specifically notes about Splat Viewer, to see what I have found as available.

None of it might work for your case but you would have nothing to lose by checking it out.
